### ISSUE TITLE
Enforce DynamoDB tables are encrypted

### ISSUE THREAD

**Issue by reedloden** [tfsec/tfsec#29]
`aws_dynamodb_table` should enforce that encryption is used.

https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#server_side_encryption

**Comment by 0xalexdelgado** [comment]
Per the docs 

> AWS DynamoDB tables are automatically encrypted at rest with an AWS owned Customer Master Key if this argument isn't specified.

Since different businesses have different encryption requirements I'm not sure if we should flag that as a finding and fail a build. I guess people could use the `#tfsec:ignore:AWS***` feature here if we do do it. I'm happy either way honestly, just wanted to discuss!

This did make me wonder, however, maybe `tfsec` could output warnings but not fail builds as a feature request? 💡

**Comment by owenrumney** [comment]
This is done
