### ISSUE TITLE
AWS024 check broken when kms_key_id needs interpolation

### ISSUE THREAD

**Issue by AirbornePorcine** [tfsec/tfsec#673]
**Describe the bug**
If you have an aws_kinesis_stream resource which relies on interpolation to set the kms_key_id (eg. `kms_key_id = aws_kms_key.mykey.key_id`), this check will fail with error:
`WARNING: skipped AWS024 check due to error(s): not a string`

**To Reproduce**
Create a new TF file with the following contents:
```
resource "aws_kinesis_stream" "stream" {

  encryption_type = "KMS"
  kms_key_id      = aws_kms_key.key.key_id

}

resource "aws_kms_key" "key" {

}
```
Run `tfsec .` in the directory you created this file

You should see that all tests pass, but a warning is noted: `WARNING: skipped AWS024 check due to error(s): not a string`

**Expected behavior**
If `aws_kms_key.key.key_id` is not the default Kinesis key, the check should pass with no warnings.
If `aws_kms_key.key.key_id` is the default Kinesis key, the check should fail.

NOTE: this assumes that the above TF was successfully applied to an AWS account and thus, that tfstate would contain a `key_id` for the `aws_kms_key` resource that was created.

**Desktop (please complete the following information):**
 - OS: PopOS
 - tfsec version: v0.39.14

**Additional context**
I did some debugging to see the root of this but there's a couple of concerning parts here:

1. The app treats rule failures as warnings, which is fine in normal execution. In tests however, there's a good possibility for false positives here. For example, if you add the above TF as a test case to `aws024_test.go`, checking for the absence of AWS024 failing, then it passes. Technically this is correct, AWS024 didn't fail because of input - but it still failed because of a bug in the implementation.
2. This feels like perhaps a bigger issue with tfsec - am I correct in understanding that it doesn't handle interpolation of variables that originate from the provider / in state? If so this is actually a major consideration that I feel should be highlighted in the docs, as it could create false positives/false negatives when using these kinds of interpolations.

A naive fix for this would be to change `internal/app/tfsec/checks/aws024.go L66` to:
`if keyIDAttr == nil || (keyIDAttr.Type() == cty.String && (keyIDAttr.Value().AsString() == "" || keyIDAttr.Value().AsString() == "alias/aws/kinesis")) {" {`
However this feels a bit disingenuous as it doesn't appear to actually tell you for sure that you aren't using the default Kinesis key.

**Comment by owenrumney** [comment]
Hi @AirbornePorcine  - I've fixed this in #676 . We have a load of reasonably intelligent helper methods now that will resolve values using the full model. I've tested it with your example and which seems to cover the risk of default keys 

```hcl
resource "aws_kinesis_stream" "stream" {

  encryption_type = "KMS"
  # kms_key_id      = aws_kms_key.key.key_id
  kms_key_id         = var.kms_key_id
}

resource "aws_kms_key" "key" {

}

variable "kms_key_id" {
  default = "alias/aws/kinesis"
}
```

**Comment by AirbornePorcine** [comment]
Thanks @owenrumney - this does solve this specific case of warnings.

I still think there's a bigger issue at play here though, possibly across multiple rules. For example, look at `azu012.go` L61-62:
```
defaultAction := block.GetAttribute("default_action")
if defaultAction != nil && defaultAction.Equals("Allow", parser.IgnoreCase) 
```
Now let's say that `default_action` attribute was set to an output derived from state (eg. maybe the network rule has an output vale for the default_action). When you run `tfsec`, this check would pass (as `defaultAction` is not nil, but also does not equal "Allow"). So you get a false negative - the rule is actually violated, but tfsec can't detect it.

There's other examples of this too:

- aws034 - false negative if you set `tlsPolicyAttr` via state interpolation
- aws051 - false negative if you set `storageEncryptedAttr` explicitly to false via state interpolation (`storageEncryptedattr == nil || storageEncryptedattr.IsFalse()` - the variable is not nil, and `IsFalse()` returns false when it's unset.)

I'm imagining there are others but I don't have time to dig into them right now. To me, this makes me think tfsec needs a big caveat about not taking into account state, or people will think either have rules violated that they can't fix, or (worse) be violating rules but not realize it.

For our part, unless there's a way we can incorporate interpretation of state into `tfsec`, we'll likely have to instead use something like `conftest` on TF plan outputs so we can be assured that all context is taken into account when calculating security violations.

**Comment by owenrumney** [comment]
Hey @AirbornePorcine, thanks for the feedback. I disagree I'm afraid - I think the two are very separate issues. There are some checks where the implementation is a bit off on its resolution of variable and resource output as with AWS024; we are reviewing the checks to use the more efficient helper functions as we go.

As you say, if you need to process the output of a terraform plan then tfsec in its current form is unlikely to fulfil your requirement. We don't parse state (remote or local) and we don't process the output of a `terraform plan`. From the outset, the intention was to provide rapid processing of the HCL2 model without the need for a *current and valid* plan. There are tools like `cloudsploit` that tackle the actual state of the infrastructure as it is in reality; tfsec aims to validate the code representation of the target state within the parameters of the available information. I think there is a role for multiple tools on concert rather than a single catch-all tool with its resultant trade-offs.

As with the processing of variable files, processing state files is fraught with the potential for misinformation. Stale tfstate files or an out dated tfvars can introduce an increased risk of false results. While we are looking at extending the processing of tfvars, autos, and envvars to reflect the way terraform does it, I think any plan to add state to the mix will need to be carefully considered.

**Comment by AirbornePorcine** [comment]
Fair enough - thanks for the detailed explanation @owenrumney !
