### ISSUE TITLE
False positive on AWS044

### ISSUE THREAD

**Issue by janakerman** [tfsec/tfsec#726]
The [documentation](https://tfsec.dev/docs/aws/AWS044/) for AWS044 states that the purpose of this check as:

> The AWS provider block should not contain hardcoded credentials. These can be passed in securely as runtime using environment variables.

However, it also flags on AWS providers that use workspace input variables to configure credentials. The suggested alternative of using environment variables to configure the provider does not support multiple providers in the same Terraform workspace.

I don't believe that this is a security issue, as workspace input variables can be sensitive. In fact, Terraform Enterprise provides support for sensitive input variables out of the box.

## Steps to reproduce the behaviour

```
provider "aws" {
  access_key = var.account_1_credentials.access_key_id
  secret_key = var.account_1_credentials.secret_access_key
}
```

## Expected behaviour

I expect the above Terraform to pass scans.

## Additional context

Tfsec version: `v0.39.21`

**Comment by owenrumney** [comment]
Hey @janakerman - I've built a test around this and it looks like maybe your variables are set with defaults?

I've added tests in https://github.com/tfsec/tfsec/pull/728 which look okay to me. The reason I suspect its defaults at play is because tfsec evaluates the whole model and would resolve your defaults

**Comment by owenrumney** [comment]
Closing, @janakerman feel free to reopen if this did not address the issue
